### ISSUE TITLE
Windows network path

### ISSUE THREAD

**Issue by EnsilZah** [anodynos/upath#8] opened 2017-05-04 09:36 UTC
Does not seem to behave correctly with windows network paths such as '\\Server\share\file.ext'
I expect it to return '//Server...' but I get '/Server...'

**Comment by anodynos** [comment] 2017-05-06 00:13
That's the intended behaviour - all paths are converted to *NIX format only, i.e `/some/path/`. Windows network paths are a special case, that we could add a special rule. 

But first, could you manually test some examples that make sense (i.e work). In other words, some input & expected output pairs that are tested manually and worked on Windows?

Thanks

**Comment by EnsilZah** [comment] 2017-05-07 07:39
Hmm, what I meant originally is '\\Server\share\file.ext'.

My main use case is joining/normalizing paths to be used in with the fs module.
So a path like '\\storage\projects\test.txt' works on windows, if I tried to join '\\storage', 'projects', 'test.txt', I would get '/storage/projects/test.txt', while I expect '//storage/projects/test.txt'.
A function like fs.readFile(...) would interpret '/Storage/projects/test.txt' as 'c:/storage/projects/test.txt' while '//storage/projects/test.txt' would access the correct network location.
I don't know what the canonical way of treating windows shares in a *NIX format is, but I assume the way fs treats it should be correct.

I suppose maybe for my use case I'd best just stick with the standard platform specific path module, since Windows itself doesn't accept the *NIX style path for stuff like Explorer or command line.

**Comment by anodynos** [comment] 2017-05-20 16:31
Is the behavior of `fs.readFile(''//Storage/projects/test.txt")` the right one on windows? 

I could add a rule to preserve the leading `\\` (just convert it to `//`) if that solves the problem... 

I think it won't cause any other side effects.

**Comment by EnsilZah** [comment] 2017-05-28 10:25
Yes, that is the correct behavior, thanks.

**Comment by anodynos** [comment] 2017-06-02 09:11
So, is the issue solved for you, may I close it?

**Comment by EnsilZah** [comment] 2017-06-03 14:53
Yup.

**Closed** 2017-06-13 10:36 UTC

**Comment by dperetti** [comment] 2021-04-27 12:40
Hmm I was just hit by this.
`'//Server/share/...'` is normalized to `'/Server/share/...'` when you `join` it to something, even if you use `joinSafe`.
This is definitely an issue. Not sure about the solution. Maybe an option to `joinPath` to preserve any leading `//` ?
